version: "3"

services:
  app:    
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    labels:
      #- "traefik.backend=machine-echo"
      - "traefik.frontend.rule=Host:app.docker.localhost"      
  db:
    image: mongo
  lb:
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: --api --docker
    ports:
      - "80:3000" # The HTTP port
      - "8080:8080"      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock      